# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cjm-hf-plugin-utils',
                'doc_host': 'https://cj-mills.github.io',
                'git_url': 'https://github.com/cj-mills/cjm-hf-plugin-utils',
                'lib_path': 'cjm_hf_plugin_utils'},
  'syms': {}}
