"""A dataclass mixin adding HuggingFace Hub cache / revision / air-gap / security fields to a plugin's config, with `RELOAD_TRIGGER` + JSON-schema metadata pre-set.

Docs: https://cj-mills.github.io/cjm-hf-plugin-utilscache_config.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/cache_config.ipynb.

# %% auto #0
__all__ = ['HFCacheConfig']

# %% ../nbs/cache_config.ipynb #exports
from dataclasses import dataclass, field
from typing import Optional

from cjm_plugin_system.core.interface import RELOAD_TRIGGER
from cjm_plugin_system.utils.validation import SCHEMA_TITLE, SCHEMA_DESC

# %% ../nbs/cache_config.ipynb #hf-cache-config
@dataclass
class HFCacheConfig:
    """Mixin adding HuggingFace Hub cache/revision/air-gap/security fields to a plugin config.

    Compose by inheritance:

        @dataclass
        class MyPluginConfig(HFCacheConfig):
            model_id: str = field(default="org/model", metadata={RELOAD_TRIGGER: "model"})
            # ... plugin-specific fields (all defaulted) ...

    Each field is `RELOAD_TRIGGER`-tagged `"model"` (a change invalidates a loaded
    model) and carries `SCHEMA_TITLE`/`SCHEMA_DESC` so the plugin-config UI renders
    it. `trust_remote_code` defaults to False and is flagged DANGER in its help text.
    """
    cache_dir: Optional[str] = field(
        default=None,
        metadata={
            RELOAD_TRIGGER: "model",
            SCHEMA_TITLE: "HF Cache Directory",
            SCHEMA_DESC: "Override the HF Hub cache location for model downloads (default: HF_HOME).",
        },
    )
    revision: Optional[str] = field(
        default=None,
        metadata={
            RELOAD_TRIGGER: "model",
            SCHEMA_TITLE: "Model Revision",
            SCHEMA_DESC: "Git revision / tag / commit to pin (default: the repo's main branch).",
        },
    )
    local_files_only: bool = field(
        default=False,
        metadata={
            RELOAD_TRIGGER: "model",
            SCHEMA_TITLE: "Local Files Only",
            SCHEMA_DESC: "Reject network access and use only cached files (air-gapped / reproducible).",
        },
    )
    trust_remote_code: bool = field(
        default=False,
        metadata={
            RELOAD_TRIGGER: "model",
            SCHEMA_TITLE: "Trust Remote Code",
            SCHEMA_DESC: "DANGER: allow execution of model-author code shipped in the repo.",
        },
    )
