"""Wrap `huggingface_hub.snapshot_download` so per-file progress flows to the plugin's `report_progress`, defeating the substrate's stall detector during downloads.

Docs: https://cj-mills.github.io/cjm-hf-plugin-utilsdownload.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/download.ipynb.

# %% auto #0
__all__ = ['snapshot_download_with_progress']

# %% ../nbs/download.ipynb #exports
from pathlib import Path
from typing import Callable, Optional

from huggingface_hub import snapshot_download
from tqdm.auto import tqdm as _tqdm

# %% ../nbs/download.ipynb #snapshot-download
def snapshot_download_with_progress(
    repo_id: str,                                                    # HF Hub repo id, e.g. "mistralai/Voxtral-Mini-3B-2507"
    *,
    report_progress: Optional[Callable[[float, str], None]] = None,  # Plugin's report_progress(fraction, message)
    cache_dir: Optional[str] = None,                                 # HF cache override (HFCacheConfig.cache_dir)
    revision: Optional[str] = None,                                  # Git rev / tag / commit to pin
    local_files_only: bool = False,                                  # Use cached files only; no network
    **kwargs,                                                        # Forwarded to huggingface_hub.snapshot_download
) -> Path:                                                           # Local path to the downloaded snapshot
    """Download an HF Hub snapshot, streaming per-file progress to `report_progress`.

    When `report_progress` is given, a `tqdm_class` subclass forwards each update
    as `report_progress(downloaded / total, "downloading <file>")`. When it is
    None, the default HF Hub progress bars are used unchanged.

    Returns the local snapshot directory; subsequent `from_pretrained` calls with
    the same `cache_dir` + `local_files_only=True` hit the populated cache.

    Adoption: the per-file tqdm callback is real progress but NOT a reliable
    stall-detector floor on its own (it can be sparse / silent on one large file).
    Wrap BOTH this call and the subsequent `from_pretrained` in a single
    `with self.heartbeat(...)` block so the substrate always sees the tuple advance.
    """
    tqdm_class = None
    if report_progress is not None:
        class _ReportingTqdm(_tqdm):
            def update(self, n=1):
                super().update(n)
                if self.total:
                    report_progress(self.n / self.total, f"downloading {self.desc or repo_id}")
        tqdm_class = _ReportingTqdm
    return Path(snapshot_download(
        repo_id,
        cache_dir=cache_dir,
        revision=revision,
        local_files_only=local_files_only,
        tqdm_class=tqdm_class,
        **kwargs,
    ))
