"""Call `model_class.from_pretrained(...)` and convert CUDA OOM into the substrate's typed `PluginResourceError` for CR-7 reactive retry.

Docs: https://cj-mills.github.io/cjm-hf-plugin-utilsloading.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/loading.ipynb.

# %% auto #0
__all__ = ['load_pretrained_with_oom']

# %% ../nbs/loading.ipynb #exports
from typing import Any, Optional, Type

import torch

from cjm_torch_plugin_utils.oom import cuda_oom_to_plugin_resource_error

# %% ../nbs/loading.ipynb #load-pretrained
def load_pretrained_with_oom(
    model_class: Type,            # A class exposing `.from_pretrained(repo_id, **kwargs)`
    repo_id: str,                 # Model repo id or local path passed to from_pretrained
    *,
    label: Optional[str] = None,  # OOM-message context (default: f"loading {repo_id!r}")
    **kwargs,                     # Forwarded verbatim to model_class.from_pretrained
) -> Any:                         # The loaded model
    """Call `model_class.from_pretrained(repo_id, **kwargs)`, converting CUDA OOM to a typed error.

    On `torch.cuda.OutOfMemoryError`, re-raises as `PluginResourceError` (via
    `cuda_oom_to_plugin_resource_error`) so the substrate's CR-7 reactive-retry
    path can evict + reload + retry. All other exceptions propagate unchanged.

    Wrap the call in `self.heartbeat(...)` at the plugin site to cover the silent
    construction phase; pre-download with `snapshot_download_with_progress` for
    real download progress.
    """
    try:
        return model_class.from_pretrained(repo_id, **kwargs)
    except torch.cuda.OutOfMemoryError as e:
        raise cuda_oom_to_plugin_resource_error(
            e, label=label or f"loading {repo_id!r}",
        ) from e
